### ISSUE TITLE
Counters: Rapid clicking causes more updates than there were clicks

### ISSUE THREAD

**Issue by raine** [paldepind/functional-frontend-architecture#9] opened 2015-06-25 11:57 UTC
In first counter example:

![counters](https://cloud.githubusercontent.com/assets/11027/8353797/8078f682-1b4a-11e5-92f4-c66411679f8f.gif)

**Comment by alexeygolev** [comment] 2015-08-04 19:57
can you log the actions stream and the model stream to see what is happening with the streams
I normally have this at the bottom of my file:)

``` javascript
flyd.on(a => console.log('action', a), actions$);

```

So I can uncomment it when I'm lost

**Comment by paldepind** [comment] 2015-08-15 17:10
I cannot reproduce this?

**Comment by alexeygolev** [comment] 2015-08-17 10:50
Neither can I

**Comment by paldepind** [comment] 2015-08-17 16:15
I am closing this. Reopen if necessary.

**Closed as completed by paldepind** 2015-08-17 16:15 UTC
